version: "3"

vars:
  CONDA_ENV: ehub
  PROJECT_DIR: "{{.ROOT_DIR}}"

includes:
  core:
    taskfile: ehub-core/Taskfile.yml
    env:
      PROJECT_ROOT: "{{.ROOT_DIR}}/ehub-core"
    dir: ehub-core
  cli:
    taskfile: ehub-cli/Taskfile.yml
    dir: ehub-cli

tasks:
  setup:
    desc: Set up the project (conda)
    cmds:
      - conda env create -f environment.yml || conda env update -f environment.yml --prune
      - cp -n .env.example .env || true

  lint:
    desc: Run linting tools
    cmds:
      - conda run -n {{.CONDA_ENV}} ruff check .
      - conda run -n {{.CONDA_ENV}} black --check .
      - conda run -n {{.CONDA_ENV}} mypy .

  temporal:
    desc: Run temporal
    cmds:
      - |
        nohup temporal server start-dev --db-filename {{.ROOT_DIR}}/temporal.db &> {{.ROOT_DIR}}/temporal.log &
        sleep 1
  temporal:stop:
    desc: Stop temporal
    cmds:
      - pkill -f "temporal server start-dev"
  temporal:status:
    desc: Check temporal status
    cmds:
      - ps -eafwww | grep "temporal server start-dev" | grep -v grep
  temporal:logs:
    desc: View temporal logs
    cmds:
      - tail -f {{.ROOT_DIR}}/temporal.log
  